/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package snake.app

import snake.utilities.StringUtils

import org.apache.commons.text.WordUtils

fun main() {
    println("HEHEHEHEHE I'm application");
}
